[package]
name = "methods-enum"
version = "0.1.5"
edition = "2021"
authors = ["Vladimir Shardinov <vvshard@gmail.com>"]
description = "Lightweight (no dependencies) attribute-like macro for “state” and “state machine” design patterns without dyn Trait (based on enum) with decoding output in doc-comments."
documentation = "https://docs.rs/methods-enum"
repository = "https://github.com/vvshard/methods-enum"
license = "MIT OR Apache-2.0"
categories = ["rust-patterns"]
keywords = ["macro", "methods", "enum", "state", "pattern"]

[lib]
proc-macro = true
